### ISSUE TITLE
Missing MANIFEST.in

### ISSUE THREAD

**Issue by anthonygego** [bastinjul/LEPL1402-IntelliJProjectGenerator#1]
You should have a ``MANIFEST.in`` file next to the ``setup.py`` file in order to include non-Python file such as HTML templates when running the setup with pip.

I guess in your case this could simply look like this : 

    recursive-include project_generator *
    recursive-include project_generator/static *

BTW, it would be less confusing to rename the ``static`` folder into ``templates``. It would also be nice to rename the python package in order to include inginious in it to reduce potential conflicts.

**Comment by bastinjul** [comment]
The changes have been achieved.
